import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Appbar from '../components/layout/Appbar'
import Table from '../components/layout/Table'
import Card from '../components/layout/Card'
import {useContext} from "react"
import missionContext from "../context/mission/missionContext"
import Pagination from "../components/layout/Pagination"
import Filter from "../components/layout/Filter"
import { signIn, signOut, useSession } from 'next-auth/client'

export default function Page() {
  const [ session, loading ] = useSession()
const {backdrop}=useContext(missionContext)
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

          <div className={styles.container}>
            <section className={styles.backdrop}>
              <Appbar />
              <main className={styles.main}>
                {backdrop && <Card />}

                <Filter />
                <Table />
                <Pagination />
              </main>
            </section>
          </div>
       

    </>
  );
}
